Make sure to fail if the list of platforms cannot be determined.

diff --git a/.github/workflows/BuildPythonWheels.yml b/.github/workflows/BuildPythonWheels.yml
--- a/.github/workflows/BuildPythonWheels.yml
+++ b/.github/workflows/BuildPythonWheels.yml
@@ -70,10 +70,16 @@ jobs:
 
     - name: Set dynamic environment
       id: set-env
+      shell: bash -o pipefail {0}
       run: |
         PLATFORMS="`docker manifest inspect ${{ env.BASE_IMAGE }} | \
           jq -r '.manifests[] | "\(.platform.os)/\(.platform.architecture)\(if .platform.variant != null then "/\(.platform.variant)" else "" end)"' | \
           sort -u | grep -v unknown | paste -sd ','`"
+        if [ ! -n "${PLATFORMS}" ]
+        then
+          echo "Cannot get list of platforms supported by the ${{ inputs.image }}." >&2
+          exit 1
+        fi
         GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
         GIT_BRANCH="${GIT_BRANCH#refs/tags/}"
         BUILD_IMAGE="${GHCR_REPO}:${GIT_BRANCH}-${BUILD_SUFX}"
diff --git a/.github/workflows/GetContainerPlatforms.yml b/.github/workflows/GetContainerPlatforms.yml
--- a/.github/workflows/GetContainerPlatforms.yml
+++ b/.github/workflows/GetContainerPlatforms.yml
@@ -25,10 +25,16 @@ jobs:
     steps:
     - name: Get Image Platforms
       id: get-platforms
+      shell: bash -o pipefail {0}
       run: |
         PLATFORMS="$(docker manifest inspect ${{ inputs.image }} | \
           jq -r '.manifests[] | "\(.platform.os)/\(.platform.architecture)\(if .platform.variant != null then "/\(.platform.variant)" else "" end)"' | \
           sort -u | grep -v unknown | paste -sd ',')"
+        if [ ! -n "${PLATFORMS}" ]
+        then
+          echo "Cannot get list of platforms supported by the ${{ inputs.image }}." >&2
+          exit 1
+        fi
         BUILD_MATRIX="$(echo ${PLATFORMS} | tr ',' '\n' | jq -R . | jq -s . | tr '\n' ' ')"
         echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
         echo "build-matrix=${BUILD_MATRIX}" >> $GITHUB_OUTPUT
